/*
 * Automatically generated C config: don't edit
 * ZPLSource version: 
 */
#define MAKECONF_TIMESTAMP "2024-03-18 14:41:44 CST"

#define CONFIG_HAVE_DOT_CONFIG 1

/*
 * Global Settings
 */
#define ZPL_RUNNING_BASE_PATH "/tmp/app"
#define ZPL_REAL_SYSCONFIG_PATH "/home/app"
#define ZPL_INSTALL_PATH "./_install"

/*
 * Arch Config
 */
#define ZPL_SYSTEM_MODULE 1
#define ZPL_SYSTEM_LINUX 1
#undef ZPL_SYSTEM_OPENWRT
#undef ZPL_SYSTEM_MINGW32
#undef ZPL_SYSTEM_MINGW64
#undef ZPL_SYSTEM_MSVC32
#undef ZPL_SYSTEM_MSVC64
#define ZPL_ARCH_MODULE 1
#undef ZPL_ARCH_ARM
#undef ZPL_ARCH_ARM64
#undef ZPL_ARCH_AARCH64
#undef ZPL_ARCH_X86
#define ZPL_ARCH_X86_64 1
#undef ZPL_ARCH_MIPS32
#undef ZPL_ARCH_MIPS64
#undef ZPL_ARCH_LOONGARCH64
#undef ZPL_ARCH_RISCV32
#undef ZPL_ARCH_RISCV64
#undef ZPL_ARM_A5
#undef ZPL_ARM_A6
#undef ZPL_ARM_A7
#undef ZPL_ARM_A8
#undef ZPL_ARM_A9

/*
 * Toolchain Config
 */
#define ZPL_HOST_TOOLCHAIN_MODULE 1
#undef ZPL_EXTERNAL_TOOLCHAIN_MODULE
#define ZPL_TOOLCHAIN_PREFIX ""
#undef ZPL_TOOLCHAIN_GLIBC
#undef ZPL_TOOLCHAIN_UCLIBC
#define ZPL_TOOLCHAIN_PATH ""
#define ZPL_TOOLCHAIN_INC_PATH ""
#define ZPL_TOOLCHAIN_LIB_PATH ""
#define ZPL_COMPILE_OPTIONS "-g"
#undef ZPL_COREDUMP_ENABLE
#define ZPL_FPU_HARD 1
#undef ZPL_FPU_SOFT
#undef ZPL_FPU_SOFTFP
#undef ZPL_FPU_NEON
#undef ZPL_ARM_VFP
#undef ZPL_ARM_NEON_VFP
#define ZPL_TOOLCHAIN_CFLAGS ""

/*
 * Platform configuration
 */

/*
 * OS Abstract Layer Module
 */
#define ZPL_OS_MODULE 1
#define ZPL_OS_JSON 1
#define ZPL_OS_UCI 1
#define ZPL_OS_TLV 1
#define ZPL_OS_RNG 1
#define ZPL_OS_QUEUE 1
#define ZPL_OS_NVRAM 1
#define ZPL_OS_AVL 1
#define ZPL_OS_TTYCOM 1
#define ZPL_OS_XYZ_MODEM 1
#define ZPL_OS_CPPJSON 1
#define ZPL_JTHREAD_MODULE 1
#define ZPL_LIB_MODULE 1
#define ZPL_IPV6_MODULE 1
#undef ZPL_LIBEVENT_MODULE
#undef ZPL_LIBEVENT_SIGNAL
#undef ZPL_LIBMXML_MODULE
#define ZPL_IP_FILTER 1
#define ZPL_IP_PLIST 1
#define ZPL_WORKQUEUE 1
#define ZPL_SHELL_MODULE 1
#undef ZPL_SHRL_MODULE
#define ZPL_ACTIVE_STANDBY 1
#undef ZPL_NSM_SNMP
#define ZPL_NSM_MODULE 1
#define ZPL_VRF_MODULE 1
#define ZPL_KEYCHAIN 1
#define ZPL_DISTRIBUTE 1
#define ZPL_NSM_L3MODULE 1
#define ZPL_NSM_NEXTHOP 1
#define ZPL_NSM_ROUTEMAP 1
#define ZPL_NSM_8021X 1
#define ZPL_NSM_ARP 1
#define ZPL_NSM_DHCP 1
#define ZPL_DHCPS_MODULE 1
#define ZPL_DHCPC_MODULE 1
#define ZPL_DHCPR_MODULE 1
#define ZPL_NSM_DNS 1
#define ZPL_NSM_DOS 1
#undef ZPL_NSM_FIREWALLD
#define ZPL_NSM_MAC 1
#define ZPL_NSM_MIRROR 1
#define ZPL_NSM_PPP 1
#define ZPL_NSM_QOS 1
#define ZPL_NSM_SERIAL 1
#define ZPL_NSM_TRUNK 1
#define ZPL_NSM_TUNNEL 1
#define ZPL_NSM_VLAN 1
#define ZPL_NSM_IGMP 1
#define ZPL_NSM_MSTP 1
#define ZPL_NSM_PORT 1
#define ZPL_NSM_VLANETH 1
#undef ZPL_NSM_WIRELESS
#define ZPL_NSM_BRIDGE 1
#define ZPL_NSM_SECURITY 1
#define ZPL_NSM_RTADV 1
#define ZPL_NSM_IRDP 1
#define ZPL_IPCBC_MODULE 1

/*
 * Component Module Config
 */
#define ZPL_COMPONENT_MODULE 1
#define ZPL_MODEM_MODULE 1
#define ZPL_MQTT_MODULE 1
#define ZPL_MQTT_SSL 1
#define ZPL_MQTT_SRV 1
#define ZPL_PJSIP_MODULE 1
#undef ZPL_PJSIP_SRTP
#define ZPL_PJSIP_VIDEO 1
#undef ZPL_PJSIP_VIDEO_V4L2
#undef ZPL_PJSIP_HISIVIDEO
#undef ZPL_PJSIP_ALSA
#undef ZPL_PJSIP_PORTAUDIO
#undef ZPL_PJSIP_HISIAUDIO
#define ZPL_PJSIP_PJSUA2 1
#undef ZPL_SQLITE_MODULE
#undef ZPL_SQLITE_EXE_MODULE
#define ZPL_LIBSSH_MODULE 1
#undef ZPL_LIBSSH_NACL
#define ZPL_LIBSSH_ZLIB 1
#define ZPL_LIBSSH_SFTP 1
#undef ZPL_LIBSSH_GCRYPT
#undef ZPL_LIBSSH_MBEDTLS
#define ZPL_LIBSSH_CRYPTO 1
#define ZPL_LIBSSH_OPENSSL_ED25519 1
#undef ZPL_LIBSSH_BLOWFISH
#define ZPL_LIBSSH_SERVER 1
#define ZPL_LIBSSH_PTHREAD 1
#undef ZPL_LIBSSH_GSSAPI
#undef ZPL_LIBSSH_GEX
#undef ZPL_LIBSSH_PCAP
#define ZPL_WEBSERVER_MODULE 1
#undef ZPL_WEBSERVER_NONESSL
#define ZPL_WEBSERVER_OPENSSL 1
#undef ZPL_WEBSERVER_MATRIXSSL
#undef ZPL_WEBSERVER_MBEDTLS
#undef ZPL_WEBSERVER_NANOSSL
#define ZPL_WEBAPP_MODULE 1
#undef ZPL_WIFI_MODULE
#define ZPL_MODBUS_MODULE 1
#undef ZPL_ONVIF_MODULE
#undef ZPL_ONVIF_SSL

/*
 * HAL/PAL Module Config
 */
#define ZPL_HALPAL_MODULE 1
#define ZPL_HAL_MODULE 1
#define ZPL_PAL_MODULE 1
#undef ZPL_IPCOM_MODULE
#define ZPL_KERNEL_MODULE 1
#define ZPL_KERNEL_NETLINK 1
#define ZPL_IPCOM_ROOT_PATH ""

/*
 * Service Module Config
 */
#define ZPL_SERVICE_MODULE 1
#define ZPL_SERVICE_SNTPC 1
#define ZPL_SERVICE_SNTPS 1
#define ZPL_SERVICE_SYSLOG 1
#define ZPL_SERVICE_FTPC 1
#define ZPL_SERVICE_FTPD 1
#define ZPL_SERVICE_TFTPC 1
#define ZPL_SERVICE_TFTPD 1
#define ZPL_SERVICE_PING 1
#define ZPL_SERVICE_TELNET 1
#undef ZPL_SERVICE_TELENTD
#define ZPL_SERVICE_TRACEROUTE 1
#define ZPL_SERVICE_UBUS_SYNC 1

/*
 * Multimedia Module Config
 */
#define ZPL_MULTIMEDIA_MODULE 1
#define ZPL_LIBRTSP_MODULE 1
#define ZPL_JRTPLIB_MODULE 1
#undef ZPL_EXOSIP_MODULE
#define ZPL_LIBRTMP_MODULE 1
#define ZPL_LIBJPEG_MODULE 1
#define ZPL_LIBMEDIA_MODULE 1
#undef ZPL_HISIMPP_MODULE
#undef ZPL_HISIMPP_HWDEBUG
#define ZPL_LIVE555_MODULE 1
#undef ZPL_SOFTCODEC_MODULE
#undef ZPL_LIBX264_MODULE
#undef ZPL_OPENH264_MODULE
#undef ZPL_LIBVPX_MODULE
#undef ZPL_FFMPEG_MODULE

/*
 * BSP Module Config
 */
#define ZPL_BSP_MODULE 1
#define ZPL_SDK_MODULE 1
#define ZPL_SDK_NONE 1
#undef ZPL_SDK_USER
#undef ZPL_SDK_KERNEL
#undef ZPL_SDK_BCM53125

/*
 * Externsions Module Config
 */
#define ZPL_EXTERNSIONS_MODULE 1
#define ZPL_ZLIB_MODULE 1
#define ZPL_EXZLIB_MODULE 1
#define ZPL_OPENSSL_MODULE 1
#undef ZPL_MBEDTLS_MODULE
#define ZPL_OPENSSH_MODULE 1
#define ZPL_FREETYPE_MODULE 1
#undef ZPL_EXFREETYPE_MODULE
#define ZPL_EXFREETYPE_INC_PATH ""
#define ZPL_EXFREETYPE_LIB_PATH ""
#undef ZPL_READLINE_MODULE
#undef ZPL_LIBNL_MODULE

/*
 * Application Module Config
 */
#undef ZPL_APPLICATION_MODULE
#undef ZPL_APP_X5_MODULE
#undef ZPL_APP_V9_MODULE

/*
 * Tools Module Config
 */
#undef ZPL_TOOLS_MODULE
#undef ZPL_TOOLS_PROCESS
#undef ZPL_TOOLS_QUECTEL_CM
#undef ZPL_TOOLS_SYSTEM
#undef ZPL_VTYSH_MODULE
#undef ZPL_WATCHDOG_MODULE
#undef ZPL_SWCONFIG_MODULE
