#ifndef _MODULE_TYPES_H
#define _MODULE_TYPES_H
 
typedef enum {
	MODULE_NONE = 0,
  MODULE_DEFAULT, 
  MODULE_LIB, 
  MODULE_OSAL, 
  MODULE_TIMER, 
  MODULE_JOB, 
  MODULE_CONSOLE, 
  MODULE_TELNET, 
  MODULE_UTILS, 
  MODULE_IMISH, 
  MODULE_KERNEL, 
  MODULE_DHCP, 
  MODULE_NSM,
  MODULE_SDK, 
  MODULE_PAL, 
  MODULE_HAL, 
	MODULE_MAX,
} module_t;
 
#endif /* _MODULE_TYPES_H */
