#include "zpl_include.h"
#include "module.h"
#include "moduletypes.h"
 
 
#define ZPL_MODULE_DESC(m)    {(MODULE_ ##m),(#m),0 }
 
 
struct module_table module_tbl[MODULE_MAX] = {
ZPL_MODULE_DESC(DEFAULT),
ZPL_MODULE_DESC(LIB),
ZPL_MODULE_DESC(OSAL),
ZPL_MODULE_DESC(TIMER),
ZPL_MODULE_DESC(JOB),
ZPL_MODULE_DESC(CONSOLE),
ZPL_MODULE_DESC(TELNET),
ZPL_MODULE_DESC(NSM),
ZPL_MODULE_DESC(HAL),
ZPL_MODULE_DESC(KERNEL),
ZPL_MODULE_DESC(PAL),
ZPL_MODULE_DESC(BSP),
ZPL_MODULE_DESC(SDK),
};
#undef ZPL_MODULE_DESC
