#ifndef _MODULE_TYPES_H
#define _MODULE_TYPES_H
 
typedef enum {
	MODULE_NONE = 0,
  MODULE_DEFAULT, 
  MODULE_LIB, 
  MODULE_OSAL, 
  MODULE_TIMER, 
  MODULE_JOB, 
  MODULE_CONSOLE, 
  MODULE_TELNET, 
  MODULE_DHCP, 
  MODULE_NSM,
  MODULE_UTILS, 
  MODULE_SNTP, 
  MODULE_SNTPS, 
  MODULE_MODEM, 
  MODULE_WIFI, 
  MODULE_MQTT, 
  MODULE_WEB, 
  MODULE_MODBUS, 
  MODULE_HAL, 
  MODULE_KERNEL, 
  MODULE_PAL, 
  MODULE_BSP,
  MODULE_SDK, 
	MODULE_MAX,
} module_t;
 
#endif /* _MODULE_TYPES_H */
