#ifndef _MODULE_TYPES_H
#define _MODULE_TYPES_H
 
 
typedef enum {
	MODULE_NONE = 0,
  MODULE_LIB, 
  MODULE_OSAL, 
  MODULE_SHELL,
  MODULE_STANDBY,
  MODULE_RIB,
  MODULE_DHCP, 
  MODULE_NSM,
  MODULE_BSP,
  MODULE_TXRX,
  MODULE_HAL, 
  MODULE_PAL, 
  MODULE_MODEM, 
  MODULE_WIFI, 
  MODULE_MQTT, 
  MODULE_WEB, 
  MODULE_MODBUS, 
  MODULE_SSH, 
  MODULE_SERVICE, 
  MODULE_SDK, 
  MODULE_RTSP,
  MODULE_MEDIA,
  MODULE_MPROXY,
  MODULE_PJAPP, 
	MODULE_MAX,
} module_t;
 
#endif /* _MODULE_TYPES_H */
