#include $(ZPL_MAKE_DIR)/module-dir.mk

ifeq ($(strip $(ZPL_EXTERNSIONS_MODULE)),true)

#
# Externsion openssl
#
ifeq ($(strip $(ZPL_OPENSSL_MODULE)),true)
ifneq ($(ZPL_BUILD_ARCH),X86_64)
ZPLEX_DIR += $(EXTERNSION_BASE_ROOT)/openssl/openssl-1.1.1/
export PLATFORM=linux-armv4
ZPLEX_INCLUDE += -I$(ZPL_INSTALL_ROOTFS_DIR)/include
ZPLEX_LDFLAGS += -L$(ZPL_INSTALL_ROOTFS_DIR)/lib
ZPLEX_LDLIBS += -lutil -lssl -lcrypto
else 
ZPLOS_LDLIBS += -lutil -lssl -lcrypto -lz
endif #($(ZPL_BUILD_ARCH),X86_64)
ZPL_DEFINE += -DZPL_OPENSSL_MODULE
endif #($(strip $(ZPL_OPENSSL_MODULE)),true)


ifeq ($(strip $(ZPL_ZLIB_MODULE)),true)
ifeq ($(ZPL_BUILD_ARCH),X86_64)
ZPLOS_LDLIBS += -lz
ZPLEX_DEFINE	+= -DZPL_ZLIB_MODULE

ZPLEX_DIR += $(EXTERNSION_BASE_ROOT)/zlib
ZLIB_ROOT = $(EXTERNSION_DIR)/zlib/zlib-1.2.11
ZPLEX_INCLUDE += -I$(EXTERNSION_BASE_ROOT)/$(ZLIB_ROOT)
ZPLEX_LDFLAGS += -L$(EXTERNSION_BASE_ROOT)/$(ZLIB_ROOT)
else
ifeq ($(strip $(ZPL_EXZLIB_MODULE)),true)
ZPLEX_DEFINE	+= -DZPL_ZLIB_MODULE
ZPLEX_INCLUDE += -I$(EXTERNSION_BASE_ROOT)/zlib/_install/include
ZPLEX_LDFLAGS += -L$(EXTERNSION_BASE_ROOT)/zlib/_install/lib
ZPLOS_LDLIBS += -lz
else
ZPLEX_DEFINE	+= -DZPL_ZLIB_MODULE
ZPLEX_DIR += $(EXTERNSION_BASE_ROOT)/zlib
ZLIB_ROOT = $(EXTERNSION_DIR)/zlib/zlib-1.2.11
ZPLEX_INCLUDE += -I$(EXTERNSION_BASE_ROOT)/$(ZLIB_ROOT)
ZPLEX_LDFLAGS += -L$(EXTERNSION_BASE_ROOT)/$(ZLIB_ROOT)
ZPLOS_LDLIBS += -lz
endif #($(strip $(ZPL_EXZLIB_MODULE)),true)
endif #($(ZPL_BUILD_ARCH),X86_64)
endif

ifeq ($(strip $(ZPL_READLINE_MODULE)),true)
ZPLEX_DEFINE	+= -DZPL_READLINE_MODULE
ifneq ($(strip $(ZPL_BUILD_ARCH)),$(filter $(ZPL_BUILD_ARCH),X86_64 X86))
READLINE_ROOT=$(EXTERNSION_DIR)/readline
ZPLEX_DIR += $(ZPLBASE)/$(READLINE_ROOT)
ZPLEX_INCLUDE += -I$(ZPLBASE)/$(READLINE_ROOT)
ZPLEX_INCLUDE += -I$(ZPLBASE)/$(READLINE_ROOT)/_install/include
ZPLEX_LDFLAGS += -L$(ZPLBASE)/$(READLINE_ROOT)/_install/lib
endif
ZPLEX_LDLIBS += -lreadline -lhistory -lncurses
endif

ifeq ($(strip $(ZPL_LIBNL_MODULE)),true)
#ZPLEX_DEFINE	+= -DZPL_LIBNL_MODULE
LIBNL_ROOT=$(EXTERNSION_DIR)/libnl
ZPLEX_DIR += $(ZPLBASE)/$(LIBNL_ROOT)
ZPLEX_INCLUDE += -I$(ZPLBASE)/$(LIBNL_ROOT)
ZPLEX_INCLUDE += -I$(ZPLBASE)/$(LIBNL_ROOT)/_install/include/libnl3
ZPLEX_LDFLAGS += -L$(ZPLBASE)/$(LIBNL_ROOT)/_install/lib
#ZPLEX_LDLIBS += -lnl-3 -lnl-genl-3 -lnl-route-3 -lnl-idiag-3 -lnl-nf -lnl-xfrm
endif

ifeq ($(strip $(ZPL_FREETYPE_MODULE)),true)
LIBMFREETYPE_ROOT=$(EXTERNSION_DIR)/freetype-2.10.0
ZPLEX_DIR += $(ZPLBASE)/$(LIBMFREETYPE_ROOT)
ZPLEX_INCLUDE += -I$(ZPLBASE)/$(LIBMFREETYPE_ROOT)/include
ZPLEX_INCLUDE += -I$(ZPLBASE)/$(LIBMFREETYPE_ROOT)/include/freetype/config
ZPL_DEFINE += -DZPL_FREETYPE_MODULE
endif

ifeq ($(strip $(ZPL_EXFREETYPE_MODULE)),true)
ZPLEX_INCLUDE += -I$(ZPL_EXFREETYPE_INC_PATH)
ZPLEX_LDFLAGS += -L$(ZPL_EXFREETYPE_LIB_PATH)
ZPL_DEFINE += -DZPL_FREETYPE_MODULE
endif


endif

