
PLATFORM_DIR = platform
SERVICE_DIR	= service
STARTUP_DIR	= startup
PRODUCT_DIR	= product
HALPAL_DIR = halpal
COMPONENT_DIR = component
TOOLS_DIR = tools
APP_DIR	= application
EXTERNSION_DIR = externsions
MULTIMEDIA_DIR = multimedia

PLATFORM_BASE_ROOT	=$(ZPLBASE)/$(PLATFORM_DIR)
SERVICE_BASE_ROOT	=$(ZPLBASE)/$(SERVICE_DIR)
STARTUP_BASE_ROOT	=$(ZPLBASE)/$(STARTUP_DIR)
PRODUCT_BASE_ROOT	=$(ZPLBASE)/$(PRODUCT_DIR)
HALPAL_BASE_ROOT		=$(ZPLBASE)/$(HALPAL_DIR)
COMPONENT_BASE_ROOT	=$(ZPLBASE)/$(COMPONENT_DIR)
TOOLS_BASE_ROOT		=$(ZPLBASE)/$(TOOLS_DIR)
APP_BASE_ROOT		=$(ZPLBASE)/$(APP_DIR)
EXTERNSION_BASE_ROOT	=$(ZPLBASE)/$(EXTERNSION_DIR)
MULTIMEDIA_BASE_ROOT	=$(ZPLBASE)/$(MULTIMEDIA_DIR)