# Automatically generated by configure - do not modify!
ifndef FFMPEG_CONFIG_MAK
FFMPEG_CONFIG_MAK=1
FFMPEG_CONFIGURATION=--prefix=$(DSTROOTFSDIR) --enable-libopenh264 --enable-ffplay --enable-postproc --enable-shared --disable-static 
#FFMPEG_CONFIGURATION=--prefix=$(DSTROOTFSDIR) --enable-libx264 --enable-gpl --enable-ffplay --enable-postproc --enable-shared --disable-static
prefix=$(DSTROOTFSDIR)
LIBDIR=$(DESTDIR)${prefix}/lib
SHLIBDIR=$(DESTDIR)${prefix}/lib
INCDIR=$(DESTDIR)${prefix}/include
BINDIR=$(DESTDIR)${prefix}/bin
DATADIR=$(DESTDIR)${prefix}/share/ffmpeg
DOCDIR=$(DESTDIR)${prefix}/share/doc/ffmpeg
MANDIR=$(DESTDIR)${prefix}/share/man
PKGCONFIGDIR=$(DESTDIR)${prefix}/lib/pkgconfig
INSTALL_NAME_DIR=
SRC_PATH=.
SRC_LINK=.
ifndef MAIN_MAKEFILE
SRC_PATH:=$(SRC_PATH:.%=..%)
endif
CC_IDENT=gcc 8 (GCC)
ifeq ($(PL_BUILD_ARCH),AARCH64)
ARCH=aarch64
INTRINSICS=neon
endif
ifeq ($(PL_BUILD_ARCH),ARM)
ARCH=ARM
INTRINSICS=none
endif

ifeq ($(PL_BUILD_ARCH),X86_64)
ARCH=x86
INTRINSICS=none
endif

EXTERN_PREFIX=
#CC=gcc
#CXX=g++
AS=$(CC)
OBJCC=$(CC)
LD=$(CC)
DEPCC=$(CC)
DEPCCFLAGS= $(CPPFLAGS)
DEPAS=$(CC)
DEPASFLAGS= $(CPPFLAGS)
X86ASM=nasm
DEPX86ASM=nasm
DEPX86ASMFLAGS=$(X86ASMFLAGS)
#AR=$(AR)
ARFLAGS=rcD
AR_O=$@
AR_CMD=$(AR)
NM_CMD=$(NM) -g
#RANLIB=$(RANLIB) -D
#STRIP=$(STRIP)
STRIPTYPE=direct
NVCC=clang
CP=cp -p
LN_S=ln -s -f
CPPFLAGS= -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 
ifeq ($(PL_BUILD_ARCH),X86_64)
CPPFLAGS += -DPIC -DZLIB_CONST
endif
CFLAGS=   -std=c11 -fomit-frame-pointer -fPIC -pthread -g -Wdeclaration-after-statement -Wall \
        -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings \
        -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes \
        -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign \
        -Wno-unused-const-variable -Wno-bool-operation -Wno-char-subscripts -O3 -fno-math-errno \
        -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration \
        -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -fdiagnostics-color=auto -Wno-maybe-uninitialized

CFLAGS += -pthread  -I/home/zhurish/workspace/SWPlatform/source/rootfs_install/include -I/usr/include -I/usr/local/include

CXXFLAGS=  -D__STDC_CONSTANT_MACROS -std=c++11 -I/usr/include -I/usr/local/include
OBJCFLAGS=  
ASFLAGS= -fPIC -g
NVCCFLAGS=--cuda-gpu-arch=sm_30 -O2 -m64 -S -nocudalib -nocudainc --cuda-device-only -include ./compat/cuda/cuda_runtime.h
AS_C=-c
AS_O=-o $@
OBJCC_C=-c
OBJCC_E=-E -o $@
OBJCC_O=-o $@
CC_C=-c
CC_E=-E -o $@
CC_O=-o $@
CXX_C=-c
CXX_O=-o $@
NVCC_C=
NVCC_O=-o $@
LD_O=-o $@
X86ASM_O=-o $@
LD_LIB=-l%
LD_PATH=-L
DLLTOOL=
ifneq ($(CROSS_COMPILE),)
WINDRES=$(CROSS_COMPILE)windres
else
WINDRES=windres
endif
DEPWINDRES=$(CC)
DOXYGEN=doxygen
LDFLAGS=  -Wl,--as-needed -Wl,-z,noexecstack -Wl,--warn-common -Wl,-rpath-link=:libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample
LDEXEFLAGS=
LDSOFLAGS=
SHFLAGS=-shared -Wl,-soname,$$(@F) -Wl,-Bsymbolic -Wl,--version-script,$(SUBDIR)lib$(NAME).ver
ASMSTRIPFLAGS= -x
ifeq ($(PL_BUILD_ARCH),X86_64)
X86ASMFLAGS=-f elf64 -DPIC -g -F dwarf
else
X86ASMFLAGS=
endif
MSAFLAGS=
MMIFLAGS=
BUILDSUF=
PROGSSUF=
FULLNAME=$(NAME)$(BUILDSUF)
LIBPREF=lib
LIBSUF=.a
LIBNAME=$(LIBPREF)$(FULLNAME)$(LIBSUF)
SLIBPREF=lib
SLIBSUF=.so
EXESUF=
EXTRA_VERSION=
CCDEP=
CXXDEP=
CCDEP_FLAGS=
ASDEP=
ASDEP_FLAGS=
X86ASMDEP=
X86ASMDEP_FLAGS=
CC_DEPFLAGS=-MMD -MF $(@:.o=.d) -MT $@
AS_DEPFLAGS=-MMD -MF $(@:.o=.d) -MT $@
ifeq ($(PL_BUILD_ARCH),X86_64)
X86ASM_DEPFLAGS=-MD $(@:.o=.d)
else
X86ASM_DEPFLAGS=
endif
HOSTCC=$(CC)
HOSTLD=$(CC)
HOSTCFLAGS=  -std=c99 -Wall -O3
HOSTCPPFLAGS= -D_ISOC99_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600
HOSTEXESUF=
HOSTLDFLAGS= 
HOSTEXTRALIBS=-lm
DEPHOSTCC=$(CC)
DEPHOSTCCFLAGS= $(HOSTCCFLAGS)
HOSTCCDEP=
HOSTCCDEP_FLAGS=
HOSTCC_DEPFLAGS=-MMD -MF $(@:.o=.d) -MT $@
HOSTCC_C=-c
HOSTCC_O=-o $@
HOSTLD_O=-o $@
TARGET_EXEC= 
TARGET_PATH=$(CURDIR)
TARGET_SAMPLES=$(SAMPLES)
CFLAGS-ffplay=
CFLAGS_HEADERS= -Wno-deprecated-declarations -Wno-unused-variable
LIB_INSTALL_EXTRA_CMD=$$(RANLIB) "$(LIBDIR)/$(LIBNAME)"
EXTRALIBS=
COMPAT_OBJS=
INSTALL=install
LIBTARGET=
SLIBNAME=$(SLIBPREF)$(FULLNAME)$(SLIBSUF)
SLIBNAME_WITH_VERSION=$(SLIBNAME).$(LIBVERSION)
SLIBNAME_WITH_MAJOR=$(SLIBNAME).$(LIBMAJOR)
SLIB_CREATE_DEF_CMD=
SLIB_EXTRA_CMD=
SLIB_INSTALL_NAME=$(SLIBNAME_WITH_VERSION)
SLIB_INSTALL_LINKS=$(SLIBNAME_WITH_MAJOR) $(SLIBNAME)
SLIB_INSTALL_EXTRA_LIB=
SLIB_INSTALL_EXTRA_SHLIB=
VERSION_SCRIPT_POSTPROCESS_CMD=cat
SAMPLES:=$(FATE_SAMPLES)
ifeq ($(PL_BUILD_ARCH),X86_64)
NOREDZONE_FLAGS=-mno-red-zone
else
NOREDZONE_FLAGS=
endif
LIBFUZZER_PATH=
IGNORE_TESTS=
avdevice_FFLIBS=avfilter swscale avformat avcodec swresample avutil
avfilter_FFLIBS=swscale avformat avcodec swresample avutil
#avdevice_FFLIBS=avfilter swscale postproc avformat avcodec swresample avutil
#avfilter_FFLIBS=swscale postproc avformat avcodec swresample avutil
swscale_FFLIBS=avutil
postproc_FFLIBS=avutil
avformat_FFLIBS=avcodec swresample avutil
avcodec_FFLIBS=swresample avutil
swresample_FFLIBS=avutil
avresample_FFLIBS=avutil
avutil_FFLIBS=
EXTRALIBS-avdevice=-lm -lxcb -lxcb-shm -lxcb-shape -lxcb-xfixes -lasound
EXTRALIBS-avfilter=-pthread -lm
EXTRALIBS-swscale=-lm
EXTRALIBS-postproc=-lm
EXTRALIBS-avformat=-lm
ifeq ($(PL_BUILD_ARCH),X86_64)
EXTRALIBS-avformat += -L/lib64 -L/usr/lib64 -L/usr/local/lib64  -lz
endif
EXTRALIBS-avcodec=-pthread -lm 
ifeq ($(PL_BUILD_ARCH),X86_64)
EXTRALIBS-avcodec += -L/lib64 -L/usr/lib64 -L/usr/local/lib64  -lz 
endif
ifeq ($(PL_LIBX264_MODULE),true)
EXTRALIBS-avcodec += -L/home/zhurish/workspace/SWPlatform/source/rootfs_install/lib -lx264
endif
ifeq ($(PL_OPENH264_MODULE),true)
EXTRALIBS-avcodec += -L/home/zhurish/workspace/SWPlatform/source/rootfs_install/lib -lopenh264
endif
EXTRALIBS-swresample=-lm
EXTRALIBS-avresample=-lm
EXTRALIBS-avutil=-pthread -lm
EXTRALIBS-ffplay=
EXTRALIBS-ffprobe=
EXTRALIBS-ffmpeg=
EXTRALIBS-cpu_init=-pthread
ifeq ($(PL_BUILD_ARCH),X86_64)
EXTRALIBS-cws2fws=-lz
else
EXTRALIBS-cws2fws=
endif

ifeq ($(PL_BUILD_ARCH),AARCH64)
include ffbuild/config-aarch64.mak
endif

ifeq ($(PL_BUILD_ARCH),X86_64)
include ffbuild/config-x86_64.mak
endif

endif # FFMPEG_CONFIG_MAK
