/* soapInit.c
   Generated by gSOAP 2.8.111 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/




#include "os_include.h"
#include <zpl_include.h>
#include "lib_include.h"
#include "soapH.h"


#define MULTICAST_GROUP (NULL) /* use a group IP such as "225.0.0.37" */
#define PORT 10000

struct soap soap;

static int onvif_module_init()
{
  soap_init1(&soap, SOAP_IO_UDP);
  /* reuse address */
  soap.bind_flags = SO_REUSEADDR;
  /* bind */
  if (!soap_valid_socket(soap_bind(&soap, NULL, PORT, 100)))
  { soap_print_fault(&soap, stderr);
    exit(1);
  }
  return 0;
}

int aaamain()
{ 
  if (MULTICAST_GROUP)
  { struct ip_mreq mreq;
    mreq.imr_multiaddr.s_addr = ipstack_inet_addr(MULTICAST_GROUP);
    mreq.imr_interface.s_addr = htonl(INADDR_ANY);
    if (setsockopt(soap.socket, IPPROTO_IP, IP_ADD_MEMBERSHIP, &mreq, sizeof(mreq)) < 0)
      exit(1);
  }
  /* serve requests */
  for (;;)
  { printf("Accepting requests\n");
    /* accept (not really needed for UDP, so can be omitted) */
    if (!soap_valid_socket(soap_accept(&soap)))
    { soap_print_fault(&soap, stderr);
      exit(1);
    }
    if (soap_serve(&soap))
      soap_print_fault(&soap, stderr);
    soap_destroy(&soap);
    soap_end(&soap);
  }
  soap_done(&soap);
  return 0;
}



struct module_list module_list_onvif = 
{ 
	.module=MODULE_ONVIF, 
	.name="ONVIF", 
	.module_init=onvif_module_init, 
	.module_exit=NULL, 
	.module_task_init=aaamain, 
	.module_task_exit=NULL, 
	.module_cmd_init=NULL, 
	.module_write_config=NULL, 
	.module_show_config=NULL,
	.module_show_debug=NULL, 
	.taskid=0,
};
/* End of soapInit.c */
