#ifndef __HAL_CMDDEF_H__
#define __HAL_CMDDEF_H__
#ifdef __cplusplus
extern "C" {
#endif




/* HAL_MODULE_8021X */
enum hal_8021x_cmd 
{
    HAL_8021X_NONE,
	HAL_8021X,
	HAL_8021X_PORT_MODE,
	HAL_8021X_PORT_MAC,
	HAL_8021X_PORT_STATE,
};

/*HAL_MODULE_PORT,//L2 */
enum hal_port_cmd 
{
    HAL_PORT_NONE,
	HAL_PORT,
	HAL_PORT_LINK,
	HAL_PORT_SPEED,
	HAL_PORT_DUPLEX,
	HAL_PORT_FLOW,
    HAL_PORT_PAUSE,
    HAL_PORT_JUMBO,
	HAL_PORT_LOOP,
	HAL_PORT_LEARNING,
	HAL_PORT_SWLEARNING,
	HAL_PORT_PROTECTED,
    HAL_PORT_VRF,
    HAL_PORT_MODE,
    HAL_PORT_MTU,
    HAL_PORT_MULTICAST,
    HAL_PORT_BANDWIDTH,
	//STORM
	HAL_PORT_STORM_RATELIMIT,  
    HAL_PORT_STATS,    
};

/* HAL_MODULE_L3IF //L3 */
enum hal_l3if_cmd 
{
    HAL_L3IF_NONE,
	HAL_L3IF_CREATE,
	HAL_L3IF_DELETE,
	HAL_L3IF_ADDR_ADD,
	HAL_L3IF_ADDR_DEL,
	HAL_L3IF_DSTADDR_ADD,
	HAL_L3IF_DSTADDR_DEL,
    HAL_L3IF_VRF,
	HAL_L3IF_MAC,
};

/*HAL_MODULE_ROUTE,//Route Table */
enum hal_route_cmd 
{
    HAL_ROUTE_NONE,
	HAL_ROUTE_ADD,
	HAL_ROUTE_DEL,
};

/*HAL_MODULE_MSTP HAL_MODULE_STP*/
enum hal_mstp_cmd 
{
    HAL_MSTP_NONE,
	HAL_MSTP_ENABLE,
    HAL_MSTP_CREATE,
    HAL_MSTP_ADD_VLAN,
    HAL_MSTP_DEL_VLAN,
	HAL_MSTP_STATE,
    HAL_STP_STATE,
};
/*HAL_MODULE_IGMP*/
enum hal_igmp_cmd 
{
    HAL_IGMP_NONE,
    HAL_IGMP_IPCHECK,
	HAL_IGMP_SNOOPING,
	HAL_IGMPQRY_SNOOPING,
	HAL_IGMPUNKNOW_SNOOPING,
	HAL_MLD_SNOOPING,
	HAL_MLDQRY_SNOOPING,
	HAL_ARP_COPYTOCPU,
	HAL_RARP_COPYTOCPU,
	HAL_DHCP_COPYTOCPU,
};
/* HAL_MODULE_GLOBAL */
enum hal_global_cmd 
{
    HAL_GLOBAL_NONE,
	HAL_GLOBAL_START,
    HAL_GLOBAL_JUMBO_SIZE,
	HAL_GLOBAL_MANEGE,
	HAL_GLOBAL_FORWARD,
	HAL_GLOBAL_MULTICAST_FLOOD,
	HAL_GLOBAL_UNICAST_FLOOD,
	HAL_GLOBAL_MULTICAST_LEARNING,
	HAL_GLOBAL_BPDU,
	HAL_GLOBAL_AGINT,  
	HAL_GLOBAL_WAN_PORT, 
};
/* HAL_MODULE_SWITCH */
typedef enum hal_core_cmd
{
	HAL_CORE_NONE,
  	HAL_CORE_COPY_TO_CPU,
	HAL_CORE_REDIRECT_TO_CPU,
  	HAL_CORE_FORWARED,
	HAL_CORE_DROP,
}hal_core_cmd_t;

/* HAL_MODULE_CPU */
enum hal_cpu_cmd 
{
    HAL_CPU_NONE,
	HAL_CPU_MODE,
	HAL_CPU_ENABLE,
	HAL_CPU_SPEED,
	HAL_CPU_DUPLEX,
	HAL_CPU_FLOW,
};



/*HAL_MODULE_DOS*/
enum hal_dos_cmd 
{
    HAL_DOS_CMD_NONE,
	HAL_DOS_CMD_IP_LAN_DRIP,
	HAL_DOS_CMD_TCP_BLAT_DROP,
	HAL_DOS_CMD_UDP_BLAT_DROP,
	HAL_DOS_CMD_TCP_NULLSCAN_DROP,
	HAL_DOS_CMD_TCP_XMASSCAN_DROP,
	HAL_DOS_CMD_TCP_SYNFINSCAN_DROP,
	HAL_DOS_CMD_TCP_SYNERROR_DROP,

	HAL_DOS_CMD_TCP_SHORTHDR_DROP,
	HAL_DOS_CMD_TCP_FRAGERROR_DROP,
	HAL_DOS_CMD_ICMPv4_FRAGMENT_DROP,
	HAL_DOS_CMD_ICMPv6_FRAGMENT_DROP,

	HAL_DOS_CMD_ICMPv4_LONGPING_DROP,
	HAL_DOS_CMD_ICMPv6_LONGPING_DROP,

	HAL_DOS_CMD_TCP_HDR_SIZE,
	HAL_DOS_CMD_ICMPv4_SIZE,
	HAL_DOS_CMD_ICMPv6_SIZE,
};
/*HAL_MODULE_MAC*/
enum hal_mac_cmd 
{
    HAL_MAC_CMD_NONE,
	HAL_MAC_CMD_AGE,
	HAL_MAC_CMD_ADD,
	HAL_MAC_CMD_DEL,
	HAL_MAC_CMD_CLEAR,
	HAL_MAC_CMD_CLEARALL,
	HAL_MAC_CMD_READ,
	HAL_MAC_CMD_DUMP,
    HAL_MAC_CMD_MAX,
};
/*HAL_MODULE_MIRROR*/
enum hal_mirror_cmd 
{
    HAL_MIRROR_CMD_NONE,
	HAL_MIRROR_CMD_DST_PORT,
	HAL_MIRROR_CMD_SRC_PORT,
	HAL_MIRROR_CMD_SRC_MAC,
    HAL_MIRROR_CMD_MAX,
};

/*HAL_MODULE_QINQ*/
enum hal_qinq_cmd 
{
    HAL_QINQ_CMD_NONE,
	HAL_QINQ_CMD_ENABLE,
	HAL_QINQ_CMD_TPID,
	HAL_QINQ_CMD_IF_ENABLE,
    HAL_QINQ_CMD_MAX,
};

/*HAL_MODULE_VLAN*/
enum hal_vlan_cmd 
{
    HAL_VLAN_NONE,
	HAL_VLAN,
	HAL_VLAN_CREATE,
	HAL_VLAN_DELETE,
	HAL_VLAN_RANGE_CREATE,
    HAL_VLAN_RANGE_DELETE,
    //PORT
    HAL_VLAN_ACCESS,
    HAL_VLAN_NATIVE,
    HAL_VLAN_ALLOWE,
    HAL_VLAN_RANGE_ALLOWE,
    HAL_VLAN_PORT_BASE,
    HAL_VLAN_TEST,
    HAL_VLAN_MAX,
};
/*HAL_MODULE_QOS*/
enum hal_qos_cmd 
{
    HAL_QOS_NONE,
	HAL_QOS_EN,
	HAL_QOS_IPG,
	HAL_QOS_BASE_TRUST,
	HAL_QOS_8021Q,
	HAL_QOS_DIFFSERV,

	//CLASS
	HAL_QOS_QUEUE_MAP_CLASS,
	HAL_QOS_CLASS_SCHED,
	HAL_QOS_CLASS_WEIGHT,

	//INPUT
	HAL_QOS_8021Q_MAP_QUEUE,
	HAL_QOS_DIFFSERV_MAP_QUEUE,
	HAL_QOS_IPPRE_MAP_QUEUE,
    HAL_QOS_MPLSEXP_MAP_QUEUE,		//
	HAL_QOS_PORT_MAP_QUEUE,

	//OUTPUT
	HAL_QOS_QUEUE_SCHED,
	HAL_QOS_QUEUE_WEIGHT,
	HAL_QOS_QUEUE_RATELIMIT,
	HAL_QOS_PRI_REMARK,

	//CPU
	HAL_QOS_CPU_RATELIMIT,

	HAL_QOS_PORT_INRATELIMIT,
	HAL_QOS_PORT_OUTRATELIMIT,
};

/*HAL_MODULE_TRUNK*/
enum hal_trunk_cmd 
{
    HAL_TRUNK_CMD_NONE,
	HAL_TRUNK_CMD_ENABLE,
	HAL_TRUNK_CMD_CREATE,
	HAL_TRUNK_CMD_ADDIF,
	HAL_TRUNK_CMD_DELIF,
	HAL_TRUNK_CMD_MODE,
    HAL_TRUNK_CMD_MAX,
};


enum hal_misc_cmd 
{
    HAL_MISC_NONE,
	HAL_MISC_JUMBO,
	HAL_MISC_JUMBO_SIZE,
	HAL_MISC_DHCP_SNOOP,
	HAL_MISC_IGMP_SNOOP,
    HAL_MISC_EEE,
};  

/*HAL_MODULE_DEBUG*/
enum zpl_debug_cmd
{
    HAL_KLOG_MODULE,
    HAL_KNETPKT_MODULE,
    HAL_KHALCLIENT_MODULE,
};




#ifdef __cplusplus
}
#endif

#endif /* __HAL_CMDDEF_H__ */