/* onvif_api.c
   Generated by gSOAP 2.8.111 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/




#include "auto_include.h"
#include <zplos_include.h>
#include "lib_include.h"
#include "soapH.h"

#include "wsddapi.h"
#include "onvif_server.h"


static struct onvif_soapsrv srv;

int onvif_module_init()
{
  memset(&srv, 0, sizeof(srv));
  strcpy(srv.dis_multicast, ONVIF_MULTICAST_GROUP);
  srv.dis_bindport = ONVIF_BIND_PORT;
  return OK;
}

int onvif_module_exit()
{
  return OK;
}

int onvif_module_task_init()
{ 
  onvif_soapsrv_init(&srv);
  onvif_soapsrv_task_init(&srv);
  return 0;
}

int onvif_module_task_exit()
{ 
  onvif_soapsrv_task_exit(&srv);
  onvif_soapsrv_exit(&srv);
  return 0;
}

struct module_list module_list_onvif = 
{ 
	.module=MODULE_ONVIF, 
	.name="ONVIF\0", 
	.module_init=onvif_module_init, 
	.module_exit=onvif_module_exit, 
	.module_task_init=onvif_module_task_init, 
	.module_task_exit=onvif_module_task_exit, 
	.module_cmd_init=NULL, 
	.taskid=0,
};
/* End of onvif_api.c */
