# the following is a list of the Platform configurations that have booleans associated with them
ifeq ($(MENUCONFIG_ZPL_BUILD),true)
include $(MENUCONFIG_ZPL_MODULE)
else

#
# Global Settings
#
_MODULELIST_GLOBAL = \
	ZPL_RUNNING_BASE_PATH="/tmp/app" \
	ZPL_REAL_SYSCONFIG_PATH="/dm/zhurish/work/busybox-1.28.4/SWPlatform/debug/etc" \
	ZPL_INSTALL_PATH="./_install" 

ZPL_RUNNING_BASE_PATH="/tmp/app"
ZPL_REAL_SYSCONFIG_PATH="/dm/zhurish/work/busybox-1.28.4/SWPlatform/debug/etc"

#
# Platform Arch Config
#
_MODULELIST_PLATFORM = \
	ZPL_SYSTEM_MODULE.true	 \
	ZPL_SYSTEM_LINUX.true	 \
	ZPL_SYSTEM_OPENWRT.false	 \
	ZPL_ARCH_MODULE.true	 \
	ZPL_ARCH_ARM.false	 \
	ZPL_ARCH_ARM64.false	 \
	ZPL_ARCH_X86.false	 \
	ZPL_ARCH_X86_64.true	

#
# Toolchain Config
#
_MODULELIST_TOOLCHAIN = \
	ZPL_HOST_TOOLCHAIN_MODULE.true	 \
	ZPL_EXTERNAL_TOOLCHAIN_MODULE.false	 \
	ZPL_EXTERNAL_TOOLCHAIN_GLIBC.false	 \
	ZPL_EXTERNAL_TOOLCHAIN_UCLIBC.false	 

#
# Product Module Config
#
_MODULELIST_PRODUCT = \
	ZPL_BSP_MODULE.true	 \
	ZPL_SDK_MODULE.true	 \
	ZPL_SDK_BCM53125.true	

#
# Platform configuration
#

#
# Platform OS Abstract Layer Module
#
_MODULELIST_OS = \
	ZPL_OS_MODULE.true	 \
	ZPL_OS_JSON.true	 \
	ZPL_OS_UCI.true	 \
	ZPL_OS_TLV.true	 \
	ZPL_OS_RNG.true	 \
	ZPL_OS_QUEUE.true	 \
	ZPL_OS_NVRAM.true	 \
	ZPL_OS_AVL.true	 \
	ZPL_OS_TTYCOM.true	 \
	ZPL_OS_XYZ_MODEM.true	 \
	ZPL_OS_CPPJSON.true	

#
# Platform Misc Lib Layer Module
#
_MODULELIST_MISC = \
	ZPL_MISC_MODULE.true	 \
	ZPL_MISC_BITMAP.true	\
	ZPL_MISC_IFHOOK.false	 \
	ZPL_MISC_SHOW_HOOK.false	 

#
# Platform NSM Layer Module
#
_MODULELIST_NSM = \
	ZPL_NSM_MODULE.true	 \
	ZPL_NSM_8021X.true	 \
	ZPL_NSM_ARP.true	 \
	ZPL_NSM_BRIDGE.true	 \
	ZPL_NSM_DHCP.true	 \
	ZPL_NSM_DNS.true	 \
	ZPL_NSM_DOS.true	 \
	ZPL_NSM_FIREWALLD.true	 \
	ZPL_NSM_MAC.true	 \
	ZPL_NSM_MIRROR.true	 \
	ZPL_NSM_PPP.true	 \
	ZPL_NSM_QOS.true	 \
	ZPL_NSM_SERIAL.true	 \
	ZPL_NSM_TRUNK.true	 \
	ZPL_NSM_TUNNEL.true	 \
	ZPL_NSM_VLAN.true	 \
	ZPL_NSM_VLANETH.true	 \
	ZPL_NSM_SECURITY.true	 

#
# Platform Shell Module
#
_MODULELIST_SHELL = \
	ZPL_SHELL_MODULE.true	

#
# Component Module Config
#
_MODULELIST_COMPONENT = \
	ZPL_COMPONENT_MODULE.true	 \
	ZPL_MODEM_MODULE.true	 \
	ZPL_MQTT_MODULE.true	 \
	ZPL_MQTT_SSL.false	 \
	ZPL_MQTT_SRV.true	 \
	ZPL_PJSIP_MODULE.true	 \
	ZPL_PJSIP_PJSUA2.true	 \
	ZPL_SQLITE_MODULE.true	 \
	ZPL_SQLITE_EXE_MODULE.false	 \
	ZPL_LIBSSH_MODULE.true	 \
	ZPL_LIBSSH_NACL.false	 \
	ZPL_LIBSSH_ZLIB.true	 \
	ZPL_LIBSSH_SFTP.true	 \
	ZPL_LIBSSH_MBEDTLS.false	 \
	ZPL_LIBSSH_GCRYPT.false	 \
	ZPL_LIBSSH_CRYPTO.true	 \
	ZPL_LIBSSH_OPENSSL_ED25519.false	 \
	ZPL_LIBSSH_BLOWFISH.false	 \
	ZPL_LIBSSH_SERVER.true	 \
	ZPL_LIBSSH_PTHREAD.true	 \
	ZPL_LIBSSH_GSSAPI.false	 \
	ZPL_LIBSSH_GEX.false	 	\
	ZPL_LIBSSH_PCAP.false	 \
	ZPL_DHCP_MODULE.true	 \
	ZPL_DHCPS_MODULE.true	 \
	ZPL_DHCPC_MODULE.true	 \
	ZPL_DHCPR_MODULE.true	 \
	ZPL_WEBSERVER_MODULE.true	 \
	ZPL_WIFI_MODULE.true	 

#
# Externsions Module Config
#
_MODULELIST_EXTERNSIONS = \
	ZPL_EXTERNSIONS_MODULE.true	 \
	ZPL_PJPROJECT_MODULE.true	 \
	ZPL_PJPROJECT_OPTIONS.true	 \
	ZPL_PJ_RESAMPLE_ENABLE.true	 \
	ZPL_PJ_SIMPLE_ENABLE.true	 \
	ZPL_PJ_SRTP_ENABLE.true	 \
	ZPL_PJ_VIDEO_ENABLE.true	 \
	ZPL_PJ_VIDEO_YUV_ENABLE.true	 \
	ZPL_PJ_VIDEO_H264_ENABLE.true	 \
	ZPL_PJ_CODEC_GSM_ENABLE.true	 \
	ZPL_PJ_CODEC_SPEEX_ENABLE.true	 \
	ZPL_PJ_CODEC_ILBC_ENABLE.true	 \
	ZPL_PJ_CODEC_G722_ENABLE.true	 \
	ZPL_PJ_CODEC_WEBRTC_ENABLE.true	 \
	ZPL_PJ_AUDIO_ALSA.true	 \
	ZPL_PJ_AUDIO_PORTAUDIO.false	 \
	ZPL_PJ_CODEC_VPX_ENABLE.false	 \
	ZPL_PJ_FFMPEG_ENABLE.false	 \
	ZPL_PJ_SDL_ENABLE.false	 \
	ZPL_OPENSSL_MODULE.false

ZPL_PJ_CODEC_H264_LIB_PATH=/usr/local
#
# Abstract Module Config
#
_MODULELIST_ABSTRACT = \
	ZPL_ABSTRACT_MODULE.true	 \
	ZPL_HAL_MODULE.true	 \
	ZPL_PAL_MODULE.true	 \
	ZPL_IPCOM_STACK_MODULE.false	 \
	ZPL_KERNEL_STACK_MODULE.true \
	ZPL_KERNEL_STACK_NETLINK.true	\
	ZPL_KERNEL_SORF_FORWARDING.false  
#
# Service Module Config
#
_MODULELIST_SERVICE = \
	ZPL_SERVICE_MODULE.true	 \
	ZPL_SERVICE_SNTPC.true	 \
	ZPL_SERVICE_SNTPS.true	 \
	ZPL_SERVICE_SYSLOG.true	 \
	ZPL_SERVICE_FTPC.true	 \
	ZPL_SERVICE_FTPD.true	 \
	ZPL_SERVICE_TFTPC.true	 \
	ZPL_SERVICE_TFTPD.true	 \
	ZPL_SERVICE_PING.true	 \
	ZPL_SERVICE_TELNET.true	 \
	ZPL_SERVICE_TELENTD.false	 \
	ZPL_SERVICE_TRACEROUTE.true	 \
	ZPL_SERVICE_UBUS_SYNC.true	 


#
# Multimedia Module Config
#
_MODULELIST_MULTIMEDIA = \
	ZPL_MULTIMEDIA_MODULE.true \
	ZPL_LIVE555_MODULE.true \
	ZPL_LIBX264_MODULE.true \
	ZPL_OPENH264_MODULE.true \
	ZPL_LIBVPX_MODULE.true \
	ZPL_FFMPEG_MODULE.true
#
# Application Module Config
#
_MODULELIST_APPLICATION = \
	ZPL_APPLICATION_MODULE.true	 \
	ZPL_APP_X5_MODULE.true	 \
	ZPL_APP_V9_MODULE.false	 

#
# Tools Module Config
#
_MODULELIST_TOOLS = \
	ZPL_TOOLS_MODULE.true	 \
	ZPL_TOOLS_PROCESS.true	 \
	ZPL_TOOLS_QUECTEL_CM.true	 \
	ZPL_TOOLS_SYSTEM.true	 

_MODULELIST = $(_MODULELIST_PLATFORM) $(_MODULELIST_PRODUCT) $(_MODULELIST_OS) $(_MODULELIST_MISC) \
				$(_MODULELIST_NSM) $(_MODULELIST_SHELL) $(_MODULELIST_COMPONENT) \
				$(_MODULELIST_EXTERNSIONS) $(_MODULELIST_ABSTRACT) $(_MODULELIST_SERVICE) \
				$(_MODULELIST_MULTIMEDIA) $(_MODULELIST_APPLICATION) $(_MODULELIST_TOOLS)


_MODULELIST_OLD = \
	ZPL_SERVICE_MODULE.true \
	ZPL_SERVICE_SNTPC.true \
	ZPL_SERVICE_SNTPS.true \
	ZPL_SERVICE_SYSLOG.true \
	ZPL_STARTUP_MODULE.true \
	ZPL_BSP_MODULE.true \
	ZPL_SDK_MODULE.false \
	ZPL_SDK_BCM53125.false \
	ZPL_SHELL_MODULE.true \
	ZPL_ABSTRACT_MODULE.true \
	ZPL_HAL_MODULE.false \
	ZPL_KERNEL_STACK_MODULE.true \
	ZPL_KERNEL_STACK_NETLINK.true \
	ZPL_IPCOM_STACK_MODULE.false \
	ZPL_COMPONENT_MODULE.true \
	ZPL_OPENSSL_MODULE.true \
	ZPL_WIFI_MODULE.false \
	ZPL_MODEM_MODULE.false \
	ZPL_TOOLS_MODULE.true \
	ZPL_TOOLS_PROCESS.false \
	ZPL_TOOLS_QUECTEL_CM.false \
	ZPL_UDHCP_MODULE.false \
	ZPL_SQLITE_MODULE.true \
	ZPL_EXTERNSIONS_MODULE.true \
	ZPL_SERVICE_FTPD.true \
	ZPL_SERVICE_FTPC.true \
	ZPL_SERVICE_TFTPD.true \
	ZPL_SERVICE_TFTPC.true \
	ZPL_SERVICE_TELNET.true \
	ZPL_SERVICE_TELNETD.false \
	ZPL_SERVICE_PING.true \
	ZPL_SERVICE_TRACEROUTE.true \
	ZPL_SERVICE_UBUS_SYNC.false \
	ZPL_LIBSSH_MODULE.false \
	ZPL_PJSIP_MODULE.true \
	ZPL_APPLICATION_MODULE.true \
	ZPL_OS_UCI.true \
	ZPL_WEBSERVER_MODULE.false \
	ZPL_MQTT_MODULE.true
#
#
#
#
#
define _MODULE_DEF
#
#
export $(subst .,:=, $1)
#endif
#endif
ZPL_BUILD_MODULE := $(ZPL_BUILD_MODULE) $(subst .,=, $1)
endef
#
#
$(foreach IModule,$(_MODULELIST), $(eval $(call _MODULE_DEF,$(IModule))))
#
endif
#

        
