
PLATFORM_ROOT	=$(ZPLBASE)/platform
SERVICE_ROOT	=$(ZPLBASE)/service
STARTUP_ROOT	=$(ZPLBASE)/startup
PRODUCT_ROOT	=$(ZPLBASE)/product
HALPAL_ROOT		=$(ZPLBASE)/halpal
COMPONENT_ROOT	=$(ZPLBASE)/component
TOOLS_ROOT		=$(ZPLBASE)/tools
APP_ROOT		=$(ZPLBASE)/application
EXTERNSION_ROOT	=$(ZPLBASE)/externsions
MULTIMEDIA_ROOT	=$(ZPLBASE)/multimedia