

ifeq ($(strip $(MODULE_PLATFORM)),true)
PLATFORM_ROOT=$(PLBASE)/$(PLATFORMDIR)

PLPRODS += $(PLATFORM_ROOT)/os
PLPRODS += $(PLATFORM_ROOT)/lib
PLPRODS += $(PLATFORM_ROOT)/shell
PLPRODS += $(PLATFORM_ROOT)/nsm

PLINCLUDE += -I$(PLATFORM_ROOT)/os
PLINCLUDE += -I$(PLATFORM_ROOT)/lib
PLINCLUDE += -I$(PLATFORM_ROOT)/shell
PLINCLUDE += -I$(PLATFORM_ROOT)/nsm
PLDEFINE	+= -DPL_NSM_MODULE
endif

ifeq ($(strip $(MODULE_L2PROTOCOL)),true)

L2PROTOCOL_ROOT=$(PLBASE)/$(L2PROTOCOLDIR)

PLPRODS += $(L2PROTOCOL_ROOT)/ospf
PLPRODS += $(L2PROTOCOL_ROOT)/bgp

PLINCLUDE += -I$(L2PROTOCOL_ROOT)/ospf
PLINCLUDE += -I$(L2PROTOCOL_ROOT)/bgp

#PLDEFINE	+= -DPL_NSM_MODULE
endif

ifeq ($(strip $(MODULE_SERVICE)),true)
SERVICE_ROOT=$(PLBASE)/$(SERVICEDIR)
PLPRODS += $(SERVICE_ROOT)/sntp
PLPRODS += $(SERVICE_ROOT)/syslog

PLINCLUDE += -I$(SERVICE_ROOT)/sntp
PLINCLUDE += -I$(SERVICE_ROOT)/syslog

PLDEFINE += -DPL_SERVICE_MODULE -DSYSLOG_CLIENT
endif

ifeq ($(strip $(MODULE_STARTUP)),true)
STARTUP_ROOT=$(PLBASE)/$(STARTUPDIR)
PLPRODS += $(STARTUP_ROOT)/src
PLINCLUDE += -I$(STARTUP_ROOT)/src
endif


ifeq ($(strip $(MODULE_PRODUCT)),true)
PRODUCT_ROOT=$(PLBASE)/$(PRODUCTDIR)
PLPRODS += $(PRODUCT_ROOT)/bsp
PLPRODS += $(PRODUCT_ROOT)/sdk

PLINCLUDE += -I$(PRODUCT_ROOT)/bsp
PLINCLUDE += -I$(PRODUCT_ROOT)/sdk

PLDEFINE += -DPL_BSP_MODULE
endif

ifeq ($(strip $(MODULE_OSPF)),true)
OSPF_ROOT=$(PLBASE)/l3protocol/$(OSPFDIR)
PLPRODS += $(OSPF_ROOT)
PLINCLUDE += -I$(OSPF_ROOT)
PLDEFINE += -DPL_OSPF_MODULE
endif


ifeq ($(strip $(MODULE_ABSTRACT)),true)
ABSTRACT_ROOT=$(PLBASE)/$(ABSTRACTDIR)

PLPRODS += $(ABSTRACT_ROOT)/pal/kernel
PLPRODS += $(ABSTRACT_ROOT)/hal

PLINCLUDE += -I$(ABSTRACT_ROOT)/pal/kernel
PLINCLUDE += -I$(ABSTRACT_ROOT)/hal
endif



ifeq ($(strip $(MODULE_COMPONENT)),true)
COMPONENT_ROOT=$(PLBASE)/$(COMPONENTDIR)
#PLPRODS += $(COMPONENT_ROOT)
#PLINCLUDE += -I$(COMPONENT_ROOT)
endif


ifeq ($(strip $(MODULE_MODEM)),true)
ifeq ($(strip $(MODULE_COMPONENT)),true)
MODEM_ROOT=$(PLBASE)/$(COMPONENTDIR)/$(MODEMDIR)
PLPRODS += $(MODEM_ROOT)
PLINCLUDE += -I$(MODEM_ROOT)
PLDEFINE += -DPL_MODEM_MODULE
endif
endif

ifeq ($(strip $(MODULE_DHCP)),true)
ifeq ($(strip $(MODULE_COMPONENT)),true)
DHCP_ROOT=$(PLBASE)/$(COMPONENTDIR)/$(DHCPDIR)
PLPRODS += $(DHCP_ROOT)
PLINCLUDE += -I$(DHCP_ROOT)
PLDEFINE += -DPL_DHCP_MODULE 
endif
endif


ifeq ($(strip $(MODULE_WIFI)),true)
ifeq ($(strip $(MODULE_COMPONENT)),true)
WIFI_ROOT=$(PLBASE)/$(COMPONENTDIR)/$(WIFIDIR)
PLPRODS += $(WIFI_ROOT)
PLINCLUDE += -I$(WIFI_ROOT)
PLINCLUDE += -I$(WIFI_ROOT)/includes
PLDEFINE += -DPL_WIFI_MODULE
endif
endif


ifeq ($(strip $(MODULE_TOOLS)),true)
TOOLS_ROOT=$(PLBASE)/$(TOOLSDIR)
PLPRODS += $(TOOLS_ROOT)/system
PLINCLUDE += -I$(TOOLS_ROOT)/system

PLPRODS += $(TOOLS_ROOT)/quectel-CM
PLINCLUDE += -I$(TOOLS_ROOT)/quectel-CM

PLPRODS += $(TOOLS_ROOT)/process
PLINCLUDE += -I$(TOOLS_ROOT)/process

PLDEFINE += -DDOUBLE_PROCESS

endif






ifeq ($(strip $(MODULE_CLI)),true)
CLI_ROOT=$(PLBASE)/$(CLIDIR)
PLPRODS += $(CLI_ROOT)/nsm
PLPRODS += $(CLI_ROOT)/service
PLPRODS += $(CLI_ROOT)/system

PLINCLUDE += -I$(CLI_ROOT)/nsm
PLINCLUDE += -I$(CLI_ROOT)/service
PLINCLUDE += -I$(CLI_ROOT)/system

ifeq ($(strip $(MODULE_MODEM)),true)
PLPRODS += $(CLI_ROOT)/modem
PLINCLUDE += -I$(CLI_ROOT)/modem
endif
endif
