/*
 * Automatically generated C config: don't edit
 * Busybox version: 
 */
#define AUTOCONF_TIMESTAMP "2021-12-31 20:45:04 CST"

#define CONFIG_HAVE_DOT_CONFIG 1

/*
 * Global Settings
 */
#define ZPL_RUNNING_BASE_PATH "/home/zhurish/workspace/working/zpl-source/source/debug/app"
#define ZPL_REAL_SYSCONFIG_PATH "/home/zhurish/workspace/working/zpl-source/source/debug/"
#define ZPL_INSTALL_PATH "./_install"

/*
 * Platform Arch Config
 */
#define ZPL_SYSTEM_MODULE 1
#define ZPL_SYSTEM_LINUX 1
#undef ZPL_SYSTEM_OPENWRT
#undef ZPL_SYSTEM_MINGW32
#undef ZPL_SYSTEM_MINGW64
#undef ZPL_SYSTEM_MSVC32
#undef ZPL_SYSTEM_MSVC64
#define ZPL_ARCH_MODULE 1
#undef ZPL_ARCH_ARM
#undef ZPL_ARCH_ARM64
#undef ZPL_ARCH_AARCH64
#undef ZPL_ARCH_X86
#define ZPL_ARCH_X86_64 1

/*
 * Toolchain Config
 */
#define ZPL_HOST_TOOLCHAIN_MODULE 1
#undef ZPL_EXTERNAL_TOOLCHAIN_MODULE
#define ZPL_EXTERNAL_TOOLCHAIN_PREFIX ""
#undef ZPL_EXTERNAL_TOOLCHAIN_GLIBC
#undef ZPL_EXTERNAL_TOOLCHAIN_UCLIBC
#define ZPL_TOOLCHAIN_PATH ""
#define ZPL_TOOLCHAIN_INC_PATH ""
#define ZPL_TOOLCHAIN_LIB_PATH ""
#define ZPL_COMPILE_OPTIONS "-g"

/*
 * Product Module Config
 */
#define ZPL_PRODUCT_MODULE 1
#define ZPL_PRODUCT_L2SWITCH 1
#define ZPL_PRODUCT_L3ROUTE 1
#define ZPL_PRODUCT_BSP_MODULE 1
#undef ZPL_PRODUCT_SDK_MODULE

/*
 * Platform configuration
 */

/*
 * OS Abstract Layer Module
 */
#define ZPL_OS_MODULE 1
#define ZPL_OS_JSON 1
#define ZPL_OS_UCI 1
#define ZPL_OS_TLV 1
#define ZPL_OS_RNG 1
#define ZPL_OS_QUEUE 1
#define ZPL_OS_NVRAM 1
#define ZPL_OS_AVL 1
#define ZPL_OS_TTYCOM 1
#define ZPL_OS_XYZ_MODEM 1
#define ZPL_OS_CPPJSON 1

/*
 * Platform Lib Module
 */
#define ZPL_WORKQUEUE 1
#define ZPL_KEYCHAIN 1
#define ZPL_DISTRIBUTE 1
#define ZPL_IP_FILTER 1
#define ZPL_IP_PLIST 1
#define ZPL_LIBEVENT_MODULE 1
#undef ZPL_LIBEVENT_SIGNAL
#undef ZPL_LIBMXML_MODULE

/*
 * Platform Shell Module
 */
#define ZPL_SHELL_MODULE 1

/*
 * NSM Layer Module
 */
#define ZPL_NSM_MODULE 1
#define ZPL_NSM_8021X 1
#define ZPL_NSM_ARP 1
#define ZPL_NSM_BRIDGE 1
#define ZPL_NSM_DHCP 1
#define ZPL_DHCPS_MODULE 1
#define ZPL_DHCPC_MODULE 1
#define ZPL_DHCPR_MODULE 1
#define ZPL_NSM_DNS 1
#define ZPL_NSM_DOS 1
#define ZPL_NSM_FIREWALLD 1
#define ZPL_NSM_MAC 1
#define ZPL_NSM_MIRROR 1
#define ZPL_NSM_PPP 1
#define ZPL_NSM_QOS 1
#define ZPL_NSM_SERIAL 1
#define ZPL_NSM_TRUNK 1
#define ZPL_NSM_TUNNEL 1
#define ZPL_NSM_VLAN 1
#define ZPL_NSM_VLANETH 1
#define ZPL_NSM_SECURITY 1

/*
 * RTPL Layer Module
 */
#define ZPL_RTPL_MODULE 1
#define ZPL_RTPL_SRV 1
#define ZPL_RTPL_RNH 1
#define ZPL_RTPL_ROUTEMAP 1
#define ZPL_IPCBC_MODULE 1
#undef ZPL_IPCBUS_MODULE

/*
 * Component Module Config
 */
#define ZPL_COMPONENT_MODULE 1
#define ZPL_MODEM_MODULE 1
#define ZPL_MQTT_MODULE 1
#undef ZPL_MQTT_SSL
#undef ZPL_MQTT_SRV
#undef ZPL_PJSIP_MODULE
#undef ZPL_PJSIP_PJSUA2
#undef ZPL_SQLITE_MODULE
#undef ZPL_SQLITE_EXE_MODULE
#undef ZPL_LIBSSH_MODULE
#undef ZPL_LIBSSH_NACL
#undef ZPL_LIBSSH_ZLIB
#undef ZPL_LIBSSH_SFTP
#undef ZPL_LIBSSH_GCRYPT
#undef ZPL_LIBSSH_MBEDTLS
#undef ZPL_LIBSSH_CRYPTO
#undef ZPL_LIBSSH_OPENSSL_ED25519
#undef ZPL_LIBSSH_BLOWFISH
#undef ZPL_LIBSSH_SERVER
#undef ZPL_LIBSSH_PTHREAD
#undef ZPL_LIBSSH_GSSAPI
#undef ZPL_LIBSSH_GEX
#undef ZPL_LIBSSH_PCAP
#define ZPL_WEBSERVER_MODULE 1
#define ZPL_WEBSERVER_NONESSL 1
#undef ZPL_WEBSERVER_OPENSSL
#undef ZPL_WEBSERVER_MATRIXSSL
#undef ZPL_WEBSERVER_MBEDTLS
#undef ZPL_WEBSERVER_NANOSSL
#define ZPL_WEBAPP_MODULE 1
#define ZPL_WIFI_MODULE 1
#define ZPL_MODBUS_MODULE 1
#undef ZPL_ONVIF_MODULE
#undef ZPL_ONVIF_SSL

/*
 * Externsions Module Config
 */
#undef ZPL_EXTERNSIONS_MODULE
#undef ZPL_ZLIB_MODULE
#undef ZPL_OPENSSL_MODULE
#undef ZPL_EXFREETYPE_MODULE
#define ZPL_EXFREETYPE_LIB_PATH ""
#define ZPL_EXFREETYPE_INC_PATH ""

/*
 * HAL/PAL Abstract Module Config
 */
#define ZPL_ABSTRACT_MODULE 1
#define ZPL_HAL_MODULE 1
#define ZPL_PAL_MODULE 1
#undef ZPL_IPCOM_STACK_MODULE
#define ZPL_KERNEL_STACK_MODULE 1
#define ZPL_KERNEL_STACK_NETLINK 1
#undef ZPL_KERNEL_SORF_FORWARDING
#define ZPL_IPCOM_ROOT_PATH ""

/*
 * Service Module Config
 */
#define ZPL_SERVICE_MODULE 1
#define ZPL_SERVICE_SNTPC 1
#define ZPL_SERVICE_SNTPS 1
#define ZPL_SERVICE_SYSLOG 1
#define ZPL_SERVICE_FTPC 1
#define ZPL_SERVICE_FTPD 1
#define ZPL_SERVICE_TFTPC 1
#define ZPL_SERVICE_TFTPD 1
#define ZPL_SERVICE_PING 1
#define ZPL_SERVICE_TELNET 1
#undef ZPL_SERVICE_TELENTD
#define ZPL_SERVICE_TRACEROUTE 1
#define ZPL_SERVICE_UBUS_SYNC 1

/*
 * Multimedia Module Config
 */
#undef ZPL_MULTIMEDIA_MODULE
#undef ZPL_LIVE555_MODULE
#undef ZPL_SOFTCODEC_MODULE
#undef ZPL_LIBX264_MODULE
#undef ZPL_OPENH264_MODULE
#undef ZPL_LIBVPX_MODULE
#undef ZPL_FFMPEG_MODULE
#undef ZPL_EXOSIP_MODULE
#undef ZPL_LIBRTMP_MODULE
#undef ZPL_PJPROJECT_MODULE
#undef ZPL_PJPROJECT_OPTIONS
#undef ZPL_PJ_RESAMPLE_ENABLE
#undef ZPL_PJ_SIMPLE_ENABLE
#undef ZPL_PJ_SRTP_ENABLE
#undef ZPL_PJ_VIDEO_ENABLE
#undef ZPL_PJ_VIDEO_YUV_ENABLE
#undef ZPL_PJ_VIDEO_H264_ENABLE
#define ZPL_PJ_CODEC_H264_LIB_PATH ""
#undef ZPL_PJ_CODEC_GSM_ENABLE
#undef ZPL_PJ_CODEC_SPEEX_ENABLE
#undef ZPL_PJ_CODEC_ILBC_ENABLE
#undef ZPL_PJ_CODEC_G722_ENABLE
#undef ZPL_PJ_CODEC_WEBRTC_ENABLE
#undef ZPL_PJ_CODEC_VPX_ENABLE
#define ZPL_PJ_CODEC_VPX_LIB_PATH ""
#undef ZPL_PJ_FFMPEG_ENABLE
#define ZPL_PJ_FFMPEG_LIB_PATH ""
#undef ZPL_PJ_SDL_ENABLE
#define ZPL_PJ_SDL_LIB_PATH ""
#undef ZPL_PJ_AUDIO_ALSA
#undef ZPL_PJ_AUDIO_PORTAUDIO
#undef ZPL_MEDIAAPP_MODULE
#undef ZPL_LIBMEDIA_MODULE
#undef ZPL_LIBRTSP_MODULE
#undef ZPL_LIBORTP_MODULE
#undef ZPL_LIBJPEG_MODULE

/*
 * hwmedia Module Config
 */
#undef ZPL_ZPLMEDIA_MODULE
#undef ZPL_HISIMPP_MODULE
#undef ZPL_HISIMPP_HWDEBUG

/*
 * Application Module Config
 */
#undef ZPL_APPLICATION_MODULE
#undef ZPL_APP_X5_MODULE
#undef ZPL_APP_V9_MODULE

/*
 * Tools Module Config
 */
#define ZPL_TOOLS_MODULE 1
#define ZPL_TOOLS_PROCESS 1
#undef ZPL_TOOLS_QUECTEL_CM
#undef ZPL_TOOLS_SYSTEM
#undef ZPL_VTYSH_MODULE
#define ZPL_WATCHDOG_MODULE 1
